name: Rust Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: trilom/file-changes-action@v1.2.3
        with:
          fileOutput: ' '
      - name: check which files have changed
        run: cat $HOME/files.txt
      - uses: icepuma/rust-action@master
        with:
          args: |
            cargo fmt -- --check && cargo clippy -- -Dwarnings &&
            TESTS=($(for filename in $(cat $HOME/files.txt) ; do if echo $filename | grep src/rosalind >/dev/null ; then echo $filename | sed 's^src/rosalind/^^' | sed 's/.rs$//' ; fi ; done))
            if [ ${#TESTS[@]} -gt 0 ] ; then cargo test ${TESTS[@]} ; fi

